name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: pedia-mcq
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Build and deploy to Cloud Run
      run: |
        gcloud builds submit --tag europe-west1-docker.pkg.dev/pedia-mcq/pedia-repo/pedia-app:${{ github.sha }}
        gcloud run deploy pedia-app \
          --image europe-west1-docker.pkg.dev/pedia-mcq/pedia-repo/pedia-app:${{ github.sha }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated 